sudo: required
dist: trusty
env:
  - VERSION_TAG=1.13.1
jobs:
  include:
    - stage: build image
      script:
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        - docker build -t alpine-nginx .
        - docker tag alpine-nginx $DOCKER_USERNAME/alpine-nginx:latest
        - docker tag alpine-nginx $DOCKER_USERNAME/alpine-nginx:$VERSION_TAG
        - docker push $DOCKER_USERNAME/alpine-nginx:latest
        - docker push $DOCKER_USERNAME/alpine-nginx:$VERSION_TAG